# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d3bc57fab5a9bdf4c5978886be3ef40641fb35fc084bf70bdc04c745f20a12dff6111194f39326d709b4609436e9962c7c96e2e8ef9e816d4b5de865ab52e888

test:
  secret_key_base: 32166b6f97ca9d9e8ebc022b312afed9773af90f57e13a93bdd0350e9668dfb87369e7adbb4bbdc597537d1b0eb68a725874d03f1a360f8c9043af8c04e60183

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
